---
collections:
  - name: community.general
    version: 8.0.2
  - name: community.sops
    version: 1.6.7
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.utils
    version: 2.11.0
  - name: kubernetes.core
    version: 3.0.0
  - name: ansible.netcommon
    version: 5.3.0
roles:
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.4.2
  - name: lae.proxmox
    src: https://github.com/lae/ansible-role-proxmox.git
    version: v1.10.0
  - name: geerlingguy.ntp
    src: https://github.com/geerlingguy/ansible-role-ntp.git
    version: 2.3.3
  - name: githubixx.cilium_cli
    version: 2.7.0+0.15.8
